app_env: development

server:
  port: 8080
  timeout: 30

redis:
  host: db.local.solu-m.io
  port: 6379
  password: "VRuAd2Nvmp4ELHh5"
  db: 0

auth:
  jwt_secret: ""
  access_token_expiration_time: 3600
  refresh_token_expiration_time: 86400

rate_limit:
  requests_per_second: 100
  burst: 10

services:
  - name: "sp-system-gateway-svc"
    base_path: "/*"
    target: "http://localhost:3001"
    methods: ["GET", "POST", "PUT", "DELETE"]
    rate_limit: 100
  - name: "sp-access-auth-svc"
    base_path: "/api/v1/auth/*"
    target: "http://localhost:3002"
    methods: ["GET", "POST", "PUT", "DELETE"]
    rate_limit: 100
    skip_auth: true
  - name: "sp-access-user-svc"
    base_path: "/api/v1/users/*"
    target: "http://localhost:3002"
    methods: ["GET", "POST", "PUT", "DELETE"]
    rate_limit: 100
  - name: "sp-access-rolepermission-svc"
    base_path: "/api/v1/role-permission/*"
    target: "http://localhost:3002"
    methods: ["GET", "POST", "PUT", "DELETE"]
    rate_limit: 100

